### ISSUE TITLE
Colab Batch Notebook Breaking With saved models error

### ISSUE THREAD

**Issue by heartlocket** [google-research/frame-interpolation#49]
I receive this error:

OSError: SavedModel file does not exist at: /content/gdrive/MyDrive/FILM/frame_interpolation/pretrained_models/film_net/Style/saved_model/{saved_model.pbtxt|saved_model.pb}

**Comment by fitsumreda** [comment]
Which Colab linked in the README are you trying to run? The PyTTI-Tools
FILM Colab seems to work fine as of a week or so ago.

**Comment by ItaiLeibowitz** [comment]
I ran into the same issue with the FILM-Gdrive Colab. I think there's some mismatch between directories where the models are saved and read from. 

I fixed it by updating the cell "Let's interpolate frames" with the following (Note the commented line vs the updated line right below it):

if os.path.isdir('/content/gdrive/MyDrive/FILM/frame_interpolation/'):
##  path = '/content/gdrive/MyDrive/FILM/frame_interpolation/pretrained_models/film_net/Style/saved_model' ##original
  path = '/content/gdrive/MyDrive/FILM/pretrained_models/film_net/Style/saved_model'  ##my update
else:
  path = '/content/frame_interpolation/pretrained_models/film_net/Style/saved_model'

**Comment by fitsumreda** [comment]
Thank you for the suggested fix.

**Comment by fitsumreda** [comment]
Does the [PyTTI-Tools FILM](https://colab.sandbox.google.com/github/pytti-tools/frame-interpolation/blob/main/PyTTI_Tools_FiLM-colab.ipynb#scrollTo=-7TD7YZJbsy_) Colab work fine for you? That is the only version I tested.

**Comment by mflux** [comment]
Hi, this issue shouldn't be closed as the issue persists in the latest version of the colab. @ItaiLeibowitz has the working fix and should be patched.
